# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leonardo Luarte González
email: leonardo@luarte.net
description: > # this means to ignore newlines until "baseurl:"
  Engineer, Developer, Cinema+Phototographer, Chef and Dancer.
  Loves to cook, eat, read and dream.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leonardo.luarte.net" # the base hostname & protocol for your site
twitter_username: lomefin
github_username:  lomefin

# Build settings
markdown: kramdown

gems:
 - jekyll-coffeescript